version: '3.7'
services:
    backend:
        image: todo-backend
        build: ./backend
        ports: 
            - "5000:5000"
        volumes:
             - ./backend:/backend
             - /backend/node_modules
        depends_on: 
            - postgres
        links: 
            - postgres
        networks: 
            - todonetwork 

    frontend:
        image: todo-frontend
        build: ./frontend
        entrypoint: ["npm","start"]
        ports: 
            - "3000:3000"
        volumes: 
            - ./frontend:/frontend
            - /frontend/node_modules
        links: 
            - backend
        networks: 
            - todonetwork
        stdin_open: true
        restart: always

    postgres: 
        image: postgres
        environment: 
                POSTGRES_PASSWORD: postgresadmin
                POSTGRES_USER: postgres
                POSTGRES_DB: todo
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports: 
            - "5432:5432"
        restart: always    
        networks: 
            -  todonetwork

networks: 
    todonetwork: 
        driver: bridge